# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11eafe0ebfce6ced379c572e86585c36f1478f74afa461e836134dcf946cdb807ea8a37b06d37783578e8f1ce425bf43817c8c8837246b02401c7a6032741367

test:
  secret_key_base: 360db7bd77e08e2569a9ff060cd19d91d8071df68960b0c646c89c0551daec4d45cb232bb6ebb538b61562d7cb28c60d4ae008b9a487d9c8da046aa3b6cd367a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
